#!/bin/bash -eu

source testlib.sh

usage()
{
    echo "Usage: $0 <IP>"
    echo ""
    exit 1
}

invalid_connect()
{
    if ../connect_timeslots $IP 1A 5 2>/dev/null
    then die "invalid connect command succeeded"; fi
}

# Start a connection. If starting it fails, there won't be a process
# to kill and we'll bomb out---just like we want
single_connect()
{
    ../connect_timeslots $IP $@ 2>/dev/null &
    sleep 1
    pid=$!
    kill $!
}

valid_connect()
{
    single_connect 1A 1 2A 1
    single_connect 1A 1 2A 13  1A 2 3A 1  2A 13 1A 1
    single_connect 1A 16 2A 16  2A 16 1A 16
}

if [ $# -lt 1 ]
then usage
fi

IP=$1
if [ $(is_duplex_card $IP) -eq 0 ]
then
    invalid_connect
    valid_connect
else
    echo "skipping connect_timeslots test because DUT isn't TX-capable"
fi
