#!/bin/bash -eu

source testlib.sh

usage()
{
    echo "Usage: $0 <IP>"
    echo ""
    exit 1
}

invalid_lapd()
{
    if ../duplex_lapd $IP 1A 2>/dev/null
    then die "invalid command succeeded"; fi
}

# If starting it fails, there won't be a process to kill and we'll
# bomb out---just like we want
valid_lapd()
{
    ../duplex_lapd $IP 1A 1 2>/dev/null &
    sleep 1
    pid=$!
    kill $!
}

if [ $# -lt 1 ]
then usage
fi

IP=$1

if [ $(is_duplex_card $IP) -eq 0 ]
then
    invalid_lapd
    valid_lapd
else
    echo "skipping connect_timeslots test because DUT isn't TX-capable"
fi
