#!/bin/bash -eu

export TOP_PID=$$
trap "exit 2" TERM

usage()
{
    echo "Usage: $0 <IP>"
    echo ""
    exit 1
}

die()
{
    echo $@ 1>&2
    kill -s TERM $TOP_PID
}

invalid_lapd()
{
    if ../duplex_lapd $IP 1A 2>/dev/null
    then die "invalid command succeeded"; fi
}

# If starting it fails, there won't be a process to kill and we'll
# bomb out---just like we want
valid_lapd()
{
    ../duplex_lapd $IP 1A 1 2>/dev/null &
    sleep 1
    pid=$!
    kill $!
}

if [ $# -lt 1 ]
then usage
fi

IP=$1

arch=`../query_set $IP board architecture | cut -d = -f 2`
case $arch in
    gth2.1)
	invalid_lapd
	valid_lapd ;;
    *)
	echo "skipping $0 because DUT is a $arch"
esac

