#!/bin/bash -eu

# Exercise the install_release sample code. Installs many different
# releases and checks that the install actually worked.

source testlib.sh

usage()
{
    echo "Usage: $0 <IP>"
    echo ""
    exit 1
}

release_archive=/home/matthias/corelatus_archive/releases/

# We test for a couple of recent releases of each type
systems()
{
    local arch=`../query_set $IP board architecture | sed -e 's/.*=//'`
    local r=$release_archive

    if [ $arch = "sth3.0" ]; then
	echo "$r/sth3_system_44c.gth $r/sth3_system_45a.gth"

    elif [ $arch = "gth3.0" ]; then
	echo "$r/gth3_system_43a.gth $r/gth3_system_44b.gth"

    else
	die "Target $IP is an unknown architecture: $arch"
    fi
}

failsafes()
{
    local arch=`../query_set $IP board architecture | sed -e 's/.*=//'`
    local r=$release_archive

    if [ $arch = "sth3.0" ]; then
        echo "$r/sth3_failsafe_15a.gth $r/sth3_failsafe_15b.gth"

    elif [ $arch = "gth3.0" ]; then
        echo "$r/gth3_failsafe_16a.gth $r/gth3_failsafe_16b.gth"

    else
	die "Target $IP is an unknown architecture: $arch"
    fi
}

ensure_failsafe_is_running()
{
    local busy=`../query_set $IP failsafe_image busy | sed -e 's/.*=//'`

    if [ $busy != "true" ]; then die "failsafe should be busy"; fi
    ensure_both_non_empty
}

ensure_system_is_running()
{
    local busy=`../query_set $IP system_image busy | sed -e 's/.*=//'`

    if [ $busy != "true" ]; then die "system should be busy"; fi
    ensure_both_non_empty
}

ensure_both_non_empty()
{
    local fs_ver=`../query_set $IP failsafe_image version | sed -e 's/.*=//'`
    local sys_ver=`../query_set $IP system_image version | sed -e 's/.*=//'`

    if [ $fs_ver = "empty" ]; then die "failsafe is empty"; fi
    if [ $sys_ver = "empty" ]; then die "system is empty"; fi
}

if [ $# -lt 1 ]
then usage
fi

IP=$1

for sys in $(systems); do
    for fs in $(failsafes); do
	../install_release -f $IP $fs
	ensure_failsafe_is_running
	../install_release $IP $sys
	ensure_system_is_running
    done
done

echo "Test completed successfully"
