#!/bin/bash -eu

# Exercise the map sample code

source testlib.sh

usage()
{
    echo "Usage: $0 <IP>"
    echo ""
    exit 1
}

map_valid()
{
    ../enable $IP sdh1 2>/dev/null
    local new_pcm=`../map $IP sdh1:hop1_1:lop1_5_3`
    ../query_set $IP $new_pcm 1>/dev/null
    ../disable $IP sdh1 1>/dev/null
}

map_invalid()
{
    if ../map $IP bogus 2>/dev/null
    then die "invalid map bogus succeeded"; fi

    if ../map $IP sdh8:hop1_1:lop1_5_3 2>/dev/null
    then die "invalid map sdh8 succeeded"; fi
}

if [ $# -lt 1 ]
then usage
fi

IP=$1
arch=`../query_set $IP board architecture | cut -d = -f 2`
case $arch in
sth3.0)
    map_valid
    map_invalid ;;
*)
    echo "skipping map test because DUT is a $arch"
esac
