#!/bin/bash -eu

source testlib.sh

usage()
{
    echo "Usage: $0 <IP>"
    echo ""
    exit 1
}

invalid_playback()
{
    if ../playback_file $IP bogus 2>/dev/null
    then die "unexpected success on bad command"; fi
}

valid_playback()
{
    ../playback_file $IP 3A 1 ../audio/dtmf5 2>/dev/null
}

if [ $# -lt 1 ]
then usage
fi

IP=$1

if [ $(is_duplex_card $IP) -eq 0 ]
then
    invalid_playback
    valid_playback
else
    echo "skipping connect_timeslots test because DUT isn't TX-capable"
fi
