#!/bin/bash -eu

source testlib.sh

usage()
{
    echo "Usage: $0 <IP>"
    echo ""
    exit 1
}

# STH 3.0 needs an E1 mapped before this test can run
arch_specific_setup()
{
    case $arch in
	sth*)
	    ../enable $IP sdh1 2>/dev/null
	    pcm=`../map $IP sdh1:hop1_1:lop1_5_3 | sed -e 's/^pcm//'`
	    ../query_set $IP pcm$pcm 1>/dev/null ;;
	*)
	    pcm="1A"
    esac
}

arch_specific_cleanup()
{
    case $arch in
	sth*)
	    ../disable $IP sdh1
    esac
}

invalid_record()
{
    if ../record $IP bogus 1 $tempdir/unused_file 2>/dev/null
    then die "invalid record 1 succeeded"; fi

    if ../record $IP $pcm 39 $tempdir/unused_file 2>/dev/null
    then die "invalid record 2 succeeded"; fi
}

valid_record()
{
    ../record $IP $pcm 1 - 2>/dev/null \
	| dd bs=1024 count=2 of=$tempdir/recording 2>/dev/null
}

if [ $# -lt 1 ]
then usage
fi

IP=$1
arch=`../query_set $IP board architecture | cut -d = -f 2`
tempdir=`mktemp --directory`

arch_specific_setup
invalid_record
valid_record
arch_specific_cleanup

rm -rf $tempdir
